# Site settings
title: Nex Level Media Ltd.
email: contact@nexlevel.media
description: > # this means to ignore newlines until "baseurl:"
 Nex Level Media Ltd. Maximising income opportunities for artists, introducing advertisers to talent in the South East Asian market.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nexlevel.media" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
highlighter: pygments
github: 
