# Site settings
title: Nex Level Media Ltd.
email: contact@nexlevel.media
description: > # this means to ignore newlines until "baseurl:"
 Maximising income opportunities for musical artists. Connecting major brands with sponsorship opportunities in South East Asia. Exclusive Cambodian BandViews Partner.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nexlevel.media" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
highlighter: pygments
github: 
